"""hybrid_auth_user_model

Revision ID: 8b1fb57b86a3
Revises: 43ad9eba8874
Create Date: 2026-09-06 02:34:29.689522
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1fb57b86a3'
down_revision: Union[str, None] = '43ad9eba8874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), server_default=sa.text("'email'"), nullable=False))
    op.create_unique_constraint('uq_users_wallet_address', 'users', ['wallet_address'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###

    # Add Supabase Trigger for syncing new users
    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger AS $$
    BEGIN
      INSERT INTO public.users (id, handle, email, auth_provider)
      VALUES (
        new.id, 
        new.raw_user_meta_data->>'handle', 
        new.email,
        COALESCE(new.raw_user_meta_data->>'auth_provider', 'email')
      );
      RETURN new;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)
    op.execute("""
    DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
    """)


def downgrade() -> None:
    # Drop the trigger first
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # We must allow null temporarily since existing rows might not have passwords, or we default it.
    op.execute("UPDATE users SET password_hash = 'dummy' WHERE password_hash IS NULL")
    op.alter_column('users', 'password_hash', nullable=False)
    
    op.drop_constraint('uq_users_wallet_address', 'users', type_='unique')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'wallet_address')
    # ### end Alembic commands ###
