"""Add onchain_tx_hash to Commitment

Revision ID: 94e9d7ba676e
Revises: 8b1fb57b86a3
Create Date: 2026-09-06 03:23:58.845929
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e9d7ba676e'
down_revision: Union[str, None] = '8b1fb57b86a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitments', sa.Column('onchain_tx_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commitments', 'onchain_tx_hash')
    # ### end Alembic commands ###
