"""Add privy_id to User

Revision ID: c0d7ff440adc
Revises: 4466d1c57b5f
Create Date: 2026-09-06 17:43:49.336288
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d7ff440adc'
down_revision: Union[str, None] = '4466d1c57b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privy_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['privy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'privy_id')
    # ### end Alembic commands ###
