"""Add JuryPool and public fields

Revision ID: e632925e395c
Revises: 94e9d7ba676e
Create Date: 2026-09-06 03:40:14.802045
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e632925e395c'
down_revision: Union[str, None] = '94e9d7ba676e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jury_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('staked_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commitments', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('commitments', sa.Column('jury_pool_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commitments', 'jury_pool_size')
    op.drop_column('commitments', 'is_public')
    op.drop_table('jury_pools')
    # ### end Alembic commands ###
